format = """
[╭─ ](fg:247)\
$os\
[](fg:#1d2230 bg:237)\
$shell\
[ ](fg:237 bg:240)\
$username\
[ ](bg:240)\
[\uE0C6 ](fg:240)
[├─┄  ](bold 247)$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php
[╰─\u2771](bold 247)$status$character"""


[character]
success_symbol = "[❱](106)"
error_symbol = "[✘](red)(238)"

[status]
map_symbol = true
style = "bold red"
symbol = '  '
success_symbol = '[  ](bold 106	)'
not_executable_symbol = ' '
not_found_symbol = ' '
sigint_symbol = '󰟾 '
signal_symbol = '⚡'
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
disabled = false

[os]
disabled = false
format = "[$symbol$version ]($style)"
style = "fg:243 bg:#1d2230"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = "[ ](12 bold) "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = "[](bright-white bold) "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = "[ ](196 bold) "
RedHatEnterprise = "[ ](196 bold) "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = "[  ](fg:208 bold bg:#1d2230) "
Unknown = " "
Windows = "[](45 bold) "

# Shell
[shell]
fish_indicator = ' 󰈺 '
powershell_indicator = '[ 󰨊 ](fg:33 bold bg:237)'
zsh_indicator = '[ ZSH󱉸 ](fg:bold 202 bg:237)'
bash_indicator = '  '
unknown_indicator = 'mystery shell'
format = '[$indicator]()'
disabled = false

# Shows the username
[username]
style_user = 'bold 113'
style_root = 'black bold'
format = '[$user](fg:120 bg:240)'
disabled = false
show_always = true

[directory]
style = "fg:123"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "

[git_branch]
symbol = " [󰊢 ](fg:red) "
format = "[\uE0A0](247)[$symbol$branch]($style)"
truncation_length = 7
truncation_symbol = "…/"
style = "fg:bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style)'
style = "fg:247 bold"
conflicted = " 󰕚 "
up_to_date = " [](fg:bold green) "
untracked = " [](fg:166 bold) "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "  "
modified = "[](fg:222 bold bg:#394260)"
staged = '[++\($count\)](fg:green)'
renamed = "  "
deleted = " [](fg:bold red) "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]()'
cherry_pick = '[ PICKING](bold red)'
merge = '[ MERGING](bold red)'
rebase = '[ REBASING](bold red)'

[nodejs]
symbol = "[ ](247) [󰎙](fg:green)"
style = "fg:191"
format = '[ $symbol ($version)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
